### ISSUE TITLE
集成spring-cloud-starter-consul-discovery的健康检查报错问题

### ISSUE THREAD

**Issue by wangxiaotao00** [alipay/sofa-rpc-boot-projects#101]
### Your question

   集成spring-cloud-starter-consul-discovery的健康检查报错， 健康检查内容如下：
  {"status":"DOWN","ConsulHealthIndicator":{"status":"DOWN","services":{"consul":[],"consul-server":["dev"],"spring-boot-sse":[],"webapi":["dev"]},"error":"java.lang.IllegalArgumentException: Value must not be null"},"sofaBootComponentHealthCheckInfo":{"status":"DOWN","Middleware-start-period":{"RUNTIME-COMPONENT":{"status":"UP","service:com.jsmfbank.sse.facade.RestService":"passed","reference:com.jsmfbank.sse.facade.RestService:#-2144235840":"passed"}}},"springContextHealthCheckInfo":{"status":"UP"},"DiskSpaceHealthIndicator":{"status":"UP","total":499963170816,"free":365070671872,"threshold":10485760},"RefreshScopeHealthIndicator":{"status":"UP"}}
    
spring-cloud-starter-consul-discovery版本是1.2.3.RELEASE

请帮忙看看这是什么问题，谢谢
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ScienJus** [comment]
@wangxiaotao00 能提供下你本地的 consul server 版本么？我之前似乎遇到过这个问题，应该是 spring cloud 在 consul 1.0 以上的版本会有问题，可以试试 0.9.x 的 consul 看是否会报错。

**Comment by wangxiaotao00** [comment]
consul server 是 1.2.3

**Comment by ScienJus** [comment]
@wangxiaotao00 应该和 https://github.com/spring-cloud/spring-cloud-consul/pull/370 以及 https://github.com/hashicorp/consul/issues/3635 是一个问题，可以试试降级 consul server 或是升级 spring cloud consul 到 1.3.x，或是干脆屏蔽掉 consul 的 health check。

总之我个人认为这个应该不是 sofa 所导致的。

**Comment by wangxiaotao00** [comment]
已解决， 将sofa-boot版本升级到2.5.1后解决， 应该是spring-boot的问题。
