### ISSUE TITLE
升级从5.4.6升级到6.0.0，client启动完就关闭了

### ISSUE THREAD

**Issue by lantianqiongfeng** [alipay/sofa-rpc-boot-projects#117]
当我将rpc-sofa-boot-starter从5.4.6升级到6.0.0的时候，发现客户端在启动完就自动关闭了，但是在5.4.6版本下启动是正常
不知道是否是版本有问题？

**Comment by khotyn** [comment]
@lantianqiongfeng 请问你们发布的是啥服务？Bolt 还是 REST 呢？

**Comment by lantianqiongfeng** [comment]
@khotyn 
附件是gradle的相关配置，
![image](https://user-images.githubusercontent.com/4092651/48814063-6027a400-ed74-11e8-9a40-3db587a3adfa.png)
这是客户端的代码
![image](https://user-images.githubusercontent.com/4092651/48814111-89e0cb00-ed74-11e8-81c8-c4ea3dd790a7.png)
我测试下来，5.4.7和6.0.0都是不行的
请问是哪里的写法问题？

**Comment by khotyn** [comment]
@lantianqiongfeng 另外，如果只是引用服务的话，本身就会自动关闭的，因为引用都是一次性的调用，而不是长期对外提供服务。如果你是一个 Web 工程，一般上 Web Server 启动后不会自动关闭，不过这个需要你添加对应的 Spring Boot 的 Web Starter。

**Comment by lantianqiongfeng** [comment]
@khotyn，这是客户端的代码，服务端的代码是在5.4.7和6.0.0都是可以的，这个引用在5.4.6上是可以的，

**Comment by lantianqiongfeng** [comment]
@khotyn ，我加入对应的 Spring Boot 的 Web Starter，已经测试升级可以了，只是有点疑问，在5.4.6是不需要加入对应的web工程，新的版本是需要的

**Comment by lantianqiongfeng** [comment]
@khotyn ，我已经明白了，这是由于5.4.6版本引用的spring boot是1.5.14版本，跟我的项目相匹配，
![image](https://user-images.githubusercontent.com/4092651/48877755-a138ba80-ee3f-11e8-9546-1c6aa363584b.png)
但是，5.4.7以后的引用的是spring boot2.0.3版本，跟项目不一致，导致了需要重新引用

**Comment by khotyn** [comment]
@lantianqiongfeng 从 5.4.6 升级到 5.4.7，Spring Boot 的版本从 1.4 升级到了 1.5，到了 6.0.0，Spring Boot 的版本变成了 2.0，应该是 Spring Boot 的版本的变化导致的。
