### ISSUE TITLE
Improve callback class set API in RpcBindingParam

### ISSUE THREAD

**Issue by khotyn** [alipay/sofa-rpc-boot-projects#119]
SOFARPC provide a method in `RpcBindingParam` for users to set callback class when users use callback invocation type, but the method accept a `String` as type:

```java
public void setCallbackClass(String callbackClass) {
}
```

We should improve this method to a more strong typed method, such as

```java
public void setCallbackClass(Class<? extends SofaResponseCallback> callbackClass) {
}
```

so users are less likely to make mistakes.

**Comment by leizhiyuan** [comment]
这个有一些历史原因，不方便改，新增的话已经有不少了，对于想使用类或者对象的，可以使用

setCallbackHandler方法，直接传入对象。
