### ISSUE TITLE
SOFA-RPC has released  v5.4.8. Will this project release v5.4.8  recently?

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc-boot-projects#132]
### Your question

SOFA-RPC has released  v5.4.8. Will this project release v5.4.8  recently?

**Comment by OrezzerO** [comment]
No , I  want to use SOFA-RPC v5.4.8 .Now, I need to add it mannuly. There will be two dependencies in my pom: rpc-sofa-boot-starter and sofa-rpc-all .

**Comment by leizhiyuan** [comment]
ok，we will release sofaboot recently

**Comment by leizhiyuan** [comment]
@
