### ISSUE TITLE
support more powerful way to config consumer parameters

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-rpc-boot-projects#136]
### Your question

now RpcBindingParam add a parameter map for extends ,but we can not set it easily in xml,so maybe we can extends a `<sofa:parameter>` to all configs.

### Your scenes

just like  hystrix,security, auth, user can 

```
 <sofa:service ref="filterService" interface="com.alipay.sofa.rpc.samples.filter.FilterService">
        <sofa:binding.bolt>
            <sofa:global-attrs filter="sampleFilter"/>
            <sofa:paramter key="xxx" value="yyy"/>
            <sofa:paramter key="xxx" value="yyy"/>
            <sofa:paramter key="xxx" value="yyy"/>
        </sofa:binding.bolt>
    </sofa:service>
```

for annotation，we can user arrays to replace Map(which is not supported by annotation)

```
SofaParamer[] paramters();

public @interface SofaParamer{
String key();
String value();
}
```

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ScienJus** [comment]
正在做这个 Feature，请问一下 XML 的话 `< sofa:parameter>` 是放在 `sofa:binding.*` 下比较好还是直接放在 `sofa:service/reference` 下比较好？

也就是：

```
<sofa:reference id="helloSyncService" jvm-first="false" interface="com.alipay.sofa.rpc.boot.invoke.HelloSyncService">
    <sofa:binding.bolt>
        <sofa:global-attrs filter="parameterFilter" />
        <sofa:parameter key="static_key" value="static_value" />
    </sofa:binding.bolt>
</sofa:reference>
```

或是：

```
<sofa:reference id="helloSyncService" jvm-first="false" interface="com.alipay.sofa.rpc.boot.invoke.HelloSyncService">
    <sofa:binding.bolt>
        <sofa:global-attrs filter="parameterFilter" />
    </sofa:binding.bolt>
    <sofa:parameter key="static_key" value="static_value" />
</sofa:reference>
```

前者的话修改 `RpcBindingConverter` 很简单，就是 xsd 需要每个 binding type 都要定义一遍 `sofa:parameter`，即使他们是完全相同的定义。

后者的话 xsd 定义会简单很多，需要修改 `AbstractContractFactoryBean#parseBindings` 过滤含有 binding.* 前缀的 node。

@QilongZhang @leizhiyuan 认为放在哪里更合理？因为 parameter 并不是 binding 相关的属性，所以我个人更赞成放在 binding 外面。

**Comment by QilongZhang** [comment]
历史使用上来看 `<sofa:parameter/>` 放在内部可能更合适一点。 因为 SOFA JVM 服务类似这种配置基本没有，如果脱离 `binding` 配置，大部分 `<sofa:parameter/>` 没什么意义.  目前来看，RPC 相关的配置，例如 `<sofa:method/>` 在 binding 内部。  @JervyShi   @leizhiyuan  你们怎么看？

**Comment by JervyShi** [comment]
@ScienJus 建议放在 `binding` 内部吧，这样当前的 xml 配置整体风格更统一一些，也可以针对协议做差异化配置。

**Comment by ScienJus** [comment]
@QilongZhang @JervyShi 好的

**Comment by ScienJus** [comment]
目前的实现在 #141 和 https://github.com/alipay/sofa-boot/pull/309 ，唯一有一点不满意的地方是，虽然 xml 和 annotation 都支持 key/value 使用动态的值，但是没有办法只修改配置文件添加和删除动态的 key/value，也许可以添加通过前缀读取 spring 配置的方式？

```
# application.yml
sofa:
  hello-service:
    parameters:
      hystrix-enabled: false
      hystrix-timeout: 500

# xml
<sofa:parameter prefix="sofa.hello-service.parameters" />

# annotation
@SofaParameter(prefix="sofa.hello-service.parameters")
```

**Comment by leizhiyuan** [comment]
加前缀的话，语意我个人觉得有点定制化了。暗示了要使用spring，先按照目前已经实现的使用好了。后续如果有新的需求，可以再看下。

如果是想要唯一定位到某个parameters，直接操作内存中对象可能更好，是否需要识别是通过这种paramter设置出来的结果，sofaboot看下是不是做一下区分，传给rpc。
