### ISSUE TITLE
有没有注解式的申明方式？

### ISSUE THREAD

**Issue by leasontou** [alipay/sofa-rpc-boot-projects#15]

**Comment by leizhiyuan** [comment]
注解方式的实现,考虑在SofaBootRpcAutoConfiguration中注册一下BeanPostProcessor,来对使用了 SofaService/SofaReference 的 bean 做发布和引用. @ujjboy @NeGnail

**Comment by QilongZhang** [comment]
SOFAArk 也会对SofaService/SofaReference处理下，这一块能不能一起确定最后注解的形式；目前SOFAArk 定的策略是：
```
沿用 sofa:service/sofa:reference/@SofaService/@SofaReference 标签和注解；

sofa:service 标签提供：binding.ark
SofaService 注解提供 binding = {JVM | ARK }，如果为空，默认发布成 JVM

sofa:reference 标签提供：binding.ark 以及 route 属性
SofaReference 注解提供 binding = {JVM | ARK} ，提供 route= {JVM | ARK}，如果为空，默认JVM，ARK, RPC路由策略

```
各自注册postprocessor处理，最后注解的样子，可以一起商定下。

**Comment by QilongZhang** [comment]
@khotyn  晚上讨论 Jarslink2.0 计划的时候，可以聊下这个事情哈

**Comment by renshihan** [comment]
建议测试用例将sever端和client端分为两个项目，这样比较直观体现rpc

**Comment by ujjboy** [comment]
好的，我们后面改一下。

**Comment by leizhiyuan** [comment]
https://github.com/leizhiyuan/sofa-rpc-boot-projects/tree/support-anotation
这个分支上我先写了一个支持注解发布和订阅的,已经测试基本 ok,部分转换还未做.需要 @SofaService 和@ SofaReference的注解支持一些参数.有空了看下.

@ujjboy @NeGnail
