### ISSUE TITLE
怎么优雅的停止consumer和provider？

### ISSUE THREAD

**Issue by empireghost** [alipay/sofa-rpc-boot-projects#32]
怎么优雅的停止consumer和provider？

**Comment by leizhiyuan** [comment]
com.alipay.sofa.rpc.context.RpcRuntimeContext#destroy()

这里 rpc 已经实现了优雅关闭的能力.

使用方可以根据自己的运维平台的能力,进行封装调用.

**Comment by leizhiyuan** [comment]
closed, if you have other question related to this, please reopen it.
