### ISSUE TITLE
sofa boot rest开发实现ContainerRequestFilter接口过滤器未生效

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-rpc-boot-projects#41]
### Your question
在ContainerRequestFilter接口实现类加上@Provider和@PreMatching注解 ，配置文件中加上bean<bean id="loginFilter" class="com.mfbank.cls.filter.LoginFilter"></bean>过滤器未生效
我采用的是2.3.2版本

@Provider
@PreMatching
public class LoginFilter implements ContainerRequestFilter{

	@Override
	public void filter(ContainerRequestContext requestContext) throws IOException {
		System.out.println("============requestContext=====s=s=s=s=s=s==");
		 String methodOverride = requestContext.getHeaderString("X-Http-Method-Override");
	    if (methodOverride != null) requestContext.setMethod(methodOverride);
		System.out.println("============requestContext=====s=s=s=s=s=s==");
	}
}
求解

**Comment by leizhiyuan** [comment]
为了管理这些 rest 的 filter,

你需要在你的fitler bean 初始化之后,可以实现InitializingBean,然后调用这个方法,把自己注册进去.

```
com.alipay.sofa.rpc.config.JAXRSProviderManager#registerCustomProviderInstance

```

**Comment by qinliang373** [comment]
感谢，采用InitializingBean过滤器可以使用了
