### ISSUE TITLE
provider应用重启后 consumer连接不上

### ISSUE THREAD

**Issue by jinchaoxiang** [alipay/sofa-rpc-boot-projects#55]
### Your question
1.首先我是本地两个应用 分别是QuickStartServer，QuickStartClient ,注册中心用的是zookeeper
2.启动QuickStartServer
3.启动QuickStartClient
4.运行一段时间后关闭QuickStartServer并重启QuickStartServer
使用的是bolt协议
sofaboot-dependencies 2.4.0|rpc-sofa-boot-starter
jdk1.8
Idea debug模式
重启server后的client的提示信息如下
2018-06-14 09:42:58.665 WARN 5156 --- [rker-1-thread-1] c.a.remoting.DefaultConnectionManager : Remove and close the last connection in ConnectionPool with poolKey 172.16.249.78:12200
client访问结果如下
{
"success": false,
"message": "RPC-02306: 没有获得服务[com.ransyh.rpc.service.integral.IIntegralService:1.0]的调用地址，请检查服务是否已经推送 ",
"result": null,
"code": "210"
}

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by jinchaoxiang** [comment]
现在解决这个问题 我这边需要重启client才能重新调用服务

**Comment by jinchaoxiang** [comment]
我发现有可能是因为客户端还是使用了直连的方式 可是我的客户端也做了如下的配置
com:
alipay:
sofa:
rpc:
registry-address: zookeeper://172.16.50.200:2181
请问客户端连接zookeeper还需要做其他配置或者引入相应的架包吗？

**Comment by JervyShi** [comment]
Fix in https://github.com/alipay/sofa-rpc/pull/180 .
