### ISSUE TITLE
关于使用@SofaReference的问题

### ISSUE THREAD

**Issue by lantianqiongfeng** [alipay/sofa-rpc-boot-projects#58]
在使用@SofaReference的客户端来引用RPC服务，使用方式如下：
@SofaReference(interfaceType = HelloSyncService.class,
            binding = @SofaReferenceBinding(bindingType = "bolt",invokeType = "sync"))
private HelloSyncService helloSyncService;

但是在调试过程中发现ConsumerConfigHelper中getConsumerConfig时，
String type = param.getType();
if (StringUtils.hasText(type)) {
            consumerConfig.setInvokeType(type);
        }
发现consumerConfig的invokeType发生了改变，变成了BOLT，导致后续报错，请问我这是否有问题

**Comment by leizhiyuan** [comment]
@lantianqiongfeng 不好意思,目前你使用的版本应该存在 bug. 使用 master 打一个包试下

**Comment by lantianqiongfeng** [comment]
好的，我重新试试

**Comment by leizhiyuan** [comment]
恩,这个会在5.4.1里 fix 掉.

**Comment by JervyShi** [comment]
Link to https://github.com/alipay/sofa-rpc-boot-projects/pull/54
