### ISSUE TITLE
服务配置多协议发布，健康检查出错

### ISSUE THREAD

**Issue by wangxiaotao00** [alipay/sofa-rpc-boot-projects#67]
### Describe the bug
多协议发布
  <sofa:service ref="restServiceImpl" interface="com.jsmfbank.sse.facade.RestService">
    	<sofa:binding.bolt/>
        <sofa:binding.rest/>
    </sofa:service>

健康检查结果：
{
    "status":"DOWN",
    "sofaBootComponentHealthCheckInfo":{
        "status":"DOWN",
        "Middleware":{
            "RUNTIME-COMPONENT":{
                "status":"DOWN",
                "reference:com.jsmfbank.sse.facade.HelloService:#1490387169":"passed",
                "reference:com.jsmfbank.sse.facade.RestService:#-486687820":"passed",
                "service:com.jsmfbank.sse.facade.HelloService":"passed",
                "service:com.jsmfbank.sse.facade.RestService":"Status: RESOLVED"
            }
        }
    },
    "springContextHealthCheckInfo":{
        "status":"UP"
    },
    "diskSpace":{
        "status":"UP",
        "total":499963170816,
        "free":406920048640,
        "threshold":10485760
    }
}

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
我看下.
