### ISSUE TITLE
sofaboot能否集成到spring

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-rpc-boot-projects#68]
### Your question

describe your question clearly
sofaboot发布了服务，能否在spring中以xml方式引用？如果可以在spring需要引入哪些包或能否提供一个demo
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
暂时不支持，SOFABoot 目前主要是在 SpringBoot 中使用。
