### ISSUE TITLE
sofaboot客户端不同版本使用api方式引用的问题

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-rpc-boot-projects#69]
### Your question

describe your question clearly
客户端使用5.3.2版本api方式引用，终端(控制台)可以正常停止，使用5.4.2 终端(控制台)不能正常停止
ConsumerConfig<IdCardVerifyFacade> consumerConfig = new ConsumerConfig<IdCardVerifyFacade>()
			    .setInterfaceId(IdCardVerifyFacade.class.getName()) // 指定接口
			    .setProtocol("rest") // 指定协议
			    .setDirectUrl("rest:// ip:port")//
			    .setConnectTimeout(2000); // 指定直连地址

		IdCardVerifyFacade f = consumerConfig.refer();
		
		IdCardVerifyRequest r = new IdCardVerifyRequest();
		r.setName("");
		r.setIdCard("");
		Result<IdCardVerify> result = f.verify(r);
		System.out.println(JSON.toJSONString(result));
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-rpc-all</artifactId>
    <version>5.4.2</version>
</dependency>

<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>1.2.0</version>
</dependency>
	<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.4</version>
		</dependency>

    	<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-context</artifactId>
		    <version>4.3.4.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-core</artifactId>
		    <version>4.3.4.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-web</artifactId>
		    <version>4.3.4.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-webmvc</artifactId>
		   <version>4.3.4.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-beans</artifactId>
		   <version>4.3.4.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-core</artifactId>
		    <version>2.9.0</version>
		</dependency>
		<dependency>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-databind</artifactId>
	    <version>2.9.0</version>
	</dependency>
- IDE version:

**Comment by leizhiyuan** [comment]
我这边测试了下,确实是这样的.原因是引入了tracer 这个组件.这个组件有个线程没有设置为daemon

```
"Tracer-TimedAppender-1-60" #16 prio=5 os_prio=31 tid=0x00007fd4ab952800 nid=0x5b03 waiting on condition [0x000070000aa4a000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076f5b8040> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


```

我这边测试打包已经验证 ok.5.4.3. 会通过修复tracer 组件的 bug.来修复.感谢反馈~

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-tracer/pull/27 

Fixed 稍后发布
