### ISSUE TITLE
LoadBalance annotation的支持

### ISSUE THREAD

**Issue by lantianqiongfeng** [alipay/sofa-rpc-boot-projects#87]
### Your question

请问LoadBalance是否支持annotation版本

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
supported in https://github.com/alipay/sofa-rpc-boot-projects/pull/121
